### ISSUE TITLE
update_markets.py fails and goes in loop.

### ISSUE THREAD

**Issue by mvitolo** [warproxxx/poly-maker#1]
Running the update_markets.py costantly fail with 

`Traceback (most recent call last):
  File "data_updater/update_markets.py", line 126, in <module>
    fetch_and_process_data()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "data_updater/update_markets.py", line 92, in fetch_and_process_data
    m_data, all_markets = get_markets(all_results, sel_df, maker_reward=0.75)
                          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "find_markets.py", line 330, in get_markets
    making_markets = s_df[~new_df['question'].isin(sel_df['question'])]
                                                   ~~~~~~^^^^^^^^^^^^
  File "frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'question'
'question'
Error getting data from Selected Markets: 'question'`

my guess is that the tool is trying to reach a column with thee name "question" but there is no (mostly because the spreadsheet is empty)

having a sort of schema in the documentation (of and example file) would probably help to better understand the issue.

**Comment by mvitolo** [comment]
I think that overall we needs a better understanding on how to user the google spreadsheet.

**Comment by warproxxx** [comment]
@mvitolo i will add a sample spreadsheet and update the instructions today

**Comment by mvitolo** [comment]
thanks!

**Comment by warproxxx** [comment]
@mvitolo just updated the readme and added a sample sheet 

update_markets.py should work now. 

Let me know if there are any issues with trading.py too. I haven't ran this repo since november. But, baring some minor issues with setup here and there, the code has been battle tested in prod for months

**Comment by mvitolo** [comment]
I am still having some issues on the trading part... I think would be beneficial a quick tutorial on how to use the entire service
